# Dockerfile

import { TipWarning } from '/components/Tip'

## Docker Image

Docker image je základní součástí kontejnerové infrastruktury. Je to obraz, který obsahuje aplikaci a všechny její potřebné části (knihovny a další soubory).

Docker image se obvykle vytváří pomocí `Dockerfile`. `Dockerfile` obsahuje příkazy pro sestavení obrazu, proměnné prostředí, příkaz, který se spustí při startu kontejneru, vstupní bod a mnoho dalších položek.

Docker images jsou pojmenovány podle následujícího schématu `registry/name:tag`. Pokud je `registry` vynechán, použije se registr docker hub. Příklad názvu docker image je: `cerit.io/xserver:v1.0`.

Před vytvořením vlastního docker image se důrazně doporučuje prohledat veřejný registr na existující obraz, který obsahuje požadovanou aplikaci, ale také zkontrolovat, jaký je časový údaj posledního obrazu, tj. zda někdo vydává nové verze a opravy chyb. Například můžeme doporučit obrazy `bitnami`. Existují určitá omezení při používání externích docker images na naší infrastruktuře, viz [omezení](limitations).

## Vytvoření vlastního Docker Image

Pokud považujete za nezbytné vytvořit vlastní obraz, níže najdete krátkého průvodce. Pro kompletní průvodce viz [oficiální dokumentace dockeru](https://docs.docker.com/develop/). Je vyžadována znalost instalace linuxových aplikací a základy linuxových balíčkovacích systémů.

Zde jsou nejběžnější příkazy Dockerfile:

1. `FROM image` -- definuje název obrazu, ze kterého začnete vytvářet svůj docker image, např. `ubuntu`.
2. `RUN cmd` -- spustí příkaz, který změní počáteční obraz, může být použito více než jeden `RUN` příkaz.
3. `COPY localfile containerfile` -- zkopíruje místní soubory do docker image, můžete použít volitelný `--chown=user:group` pro změnu vlastnictví během kopírování. Kopírování a změna vlastnictví později pomocí `RUN chown` se nedoporučuje, protože výsledný obraz bude dvakrát větší.
4. `USER uid` -- změní uživatele na `uid` (nebo jméno), od tohoto řádku budou všechny ostatní příkazy spuštěny jako specifikovaný uživatel, pokud tento příkaz není použit, vše bude provedeno jako uživatel `root`. Poslední direktiva `USER uid` také specifikuje, jako který uživatel bude kontejner běžet jako výchozí.
5. `CMD command` -- spustí `command` jako výchozí příkaz při spuštění kontejneru.
6. `WORKDIR dir` -- specifikuje aktuální pracovní adresář, poslední pracovní adresář bude použit jako počáteční adresář v běžícím kontejneru.

Příklad pro Dockerfile:
```docker filename="Dockerfile" copy
FROM debian:buster
RUN apt update -y && apt upgrade -y && apt install build-essential libssh-dev git -y
RUN git clone https://gitlab.con/zvon/iobench && cd iobench && make && make install
USER 1000
CMD /bin/bash -c "tail -f /dev/null"
```

## Tipy pro Dockerfile

* Kontejnery obvykle nemají uživatele vytvořeného v `/etc/passwd`. V tomto případě uvidíte výzvu `I have no name`. Také v tomto případě neexistuje adresář `home`, který defaultně směřuje na `/`, mnoho aplikací zde selhává, protože `/` nebude zapisovatelný. Doporučuje se vytvořit výchozího uživatele, pod kterým bude kontejner spuštěn. Jméno uživatele není důležité. Následující příkaz vytvoří skupinu s názvem `group` a uživatele s názvem `user`, dvojité `user` na konci příkazu není chyba.
```docker
RUN addgroup --gid 1000 group && \
    adduser --gid 1000 --uid 1000 --disable-password --gecos user user
```

* Kontejner defaultně používá časové pásmo UTC. Pokud to není žádoucí, mělo by být nastaveno na správné výchozí, např.
```docker
RUN echo 'Europe/Prague' > /etc/timezone
```

* Nástroje pro balení nesmí být interaktivní. Například pro systémy `deb`:
```docker
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y curl
```
Nezapomeňte přidat `-y` k většině nástrojů pro balení.

* Systémy rodiny Debian obvykle defaultně instalují doporučené balíčky, což zde není žádoucí, zakázat to:
```docker
RUN apt-get install -y --no-install-recommends curl
```

* Udržujte výsledný obraz co nejmenší. Je potřeba vyčistit dočasné soubory. Například pro `deb`:
```docker
RUN apt-get update && apt-get -y install curl && apt-get clean && rm -rf /var/lib/apt/lists/*
```
pro `conda`:
```docker
RUN conda install package && conda clean --all -f -y && rm -rf "~/.cache
```

<TipWarning>Úklid musí být proveden v rámci jednoho **RUN** příkazu.</TipWarning>

* Každý `RUN` příkaz vytváří novou vrstvu Docker image. Doporučuje se sloučit související příkazy do jednoho `RUN` příkazu, například nainstalovat všechny požadované balíčky najednou, ne jeden po druhém.

* Pro Kubernetes není potřeba používat příkaz `EXPOSE` k publikování síťových portů. Viz [Exposing Applications](../kubernetes/kubectl-expose).

* Spuštění `chown` nebo `chmod` zdvojnásobí velikost změněných souborů v docker souboru, tj. `chown` na všechny soubory v docker souboru zdvojnásobí velikost docker souboru.

* Při řetězení příkazů vždy řetězte pomocí `&&` a nikdy pouze pomocí `;`. Pokud jeden z příkazů selže, řetězení pomocí `&&` zastaví sestavení celého obrazu, což je obvykle to, co chcete. Řetězení pomocí `;` může skrýt některé selhávající příkazy a ztížit ladění, proč obraz není takový, jaký by měl být.

## Sestavení Docker Image

Docker image může být sestaven buď ručně, nebo pomocí některých automatizovaných nástrojů pro sestavení.

### Ruční sestavení

Jakmile je `Dockerfile` vytvořen, může být sestaven docker obraz. Následující popisuje, jak ručně sestavit docker obraz. Ruční sestavení může být užitečné pro ladění procesu sestavení.

Pro sestavení docker obrazu lokálně potřebujete stroj běžící na Linuxu s nainstalovaným dockerem. Pro instalaci dockeru postupujte podle pokynů pro vaši distribuci Linuxu, obvykle je správným balíčkem `docker-ce`. Možná budete muset být členem skupiny `docker`, abyste mohli docker používat.

Umístěte `Dockerfile` do adresáře, např. `mydocker`, a spusťte následující příkaz, přičemž `repo/name:tag` nahraďte správným názvem a tagem
```bash
docker build -t repo/name:tag mydocker
```

Pokud bylo sestavení úspěšné, obraz je sestaven lokálně a je třeba jej nahrát do registru. Pokud nejste přihlášeni do registru, zadejte `docker login registry`, přičemž `registry` nahraďte skutečným názvem registru.
```bash
docker push repo/name:tag
```
`repo/name:tag` musí být přesně stejné jako v případě sestavení.

### Automatizované sestavení

Automatizované sestavení může být provedeno pomocí CI/CD pipeline. Sestavení se provádí pomocí komponenty *runner*, která je součástí mnoha instalací github/gitlab. Můžete použít [gitlab.ics.muni.cz](https://gitlab.ics.muni.cz), viz [GitLab Containers](../gitops/containers_build) jak to udělat. Tento gitlab také poskytuje docker registry, takže jednou sestavený obraz může být uložen zde pro použití z Kubernetes. Registr je veřejný nebo soukromý v závislosti na nastavení projektu, viz [GitLab Containers](../gitops/containers_build#how-to-use-images-from-gitlab-registry).

Automatizované sestavení může být pomalé, takže to není nejlepší volba pro ladění procesu sestavení.

## Spouštění Docker obrazů

Může být užitečné ručně spustit sestavený obraz před jeho spuštěním na Kubernetes, například pro kontrolu, že jsou všechny soubory na svém místě, důležité adresáře jsou zapisovatelné atd. Ruční spuštění je rychlé a nemá žádná omezení oprávnění. Buďte však opatrní při spouštění neznámých obrazů na vašem stroji. Pro spuštění docker obrazu lokálně potřebujete stroj s Linuxem a nainstalovaným dockerem, viz ruční sestavení výše.

Spuštění lokálně může být také užitečné pro inspekci obrazu, například pro získání `UID` běžícího uživatele, pokud není znám, protože `UID` může být potřebný pro spuštění v Kubernetes.

Pro testovací účely můžete spustit Docker obraz pomocí:
```bash
docker run -it --rm registry/name:tag command
```

Tento příkaz spustí obraz `registry/name:tag` a provede `command` uvnitř něj. Můžete přidat `-u uid`, abyste spustili obraz jako uživatel `uid`.

Pokud použitý obraz má nastavený `ENTRYPOINT`, `command` nebude vykonán, ale bude pouze předán jako argument skriptu `ENTRYPOINT`. Pokud potřebujete zabránit vykonání, můžete předat možnost `--entrypoint /bin/bash` příkazu `docker run`. Nicméně ne všechny obrazy mají k dispozici `/bin/bash` nebo dokonce `/bin/sh`. V takovém případě budete muset obraz znovu sestavit a přidat/nainstalovat `bash` nebo `sh`.

Stisknutí `ctrl-c` nebo `ctrl-d` zabije běžící Docker obraz. Všechny změny uvnitř kontejneru budou ztraceny, pokud nepoužijete `docker commit`, viz [oficiální dokumentace dockeru](https://docs.docker.com/develop/), v tomto případě nepoužívejte možnost `--rm`, která automaticky odstraňuje ukončené obrazy.
